### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/SoundWave#6]
- [x] Lista de artistas
- [x] Arreglar añadir usuario(s)
- [x] Permitir crear playlists
- [x] Permitir añadir canciones de playlists
- [x] Permitir eliminar playlists
- [ ] Permitir editar información de usuario (nombre, apellido, correo, contraseña)
- [ ] Arreglar icono en la lista de artistas
- [ ] Agregar búsqueda de artistas
- [ ] Agregar búsqueda de álbumes
- [ ] Agregar búsqueda de géneros
- [ ] Ordenar artistas por nombre
- [ ] Ordenar géneros por nombre
- [ ] Ordenar álbumes por nombre
- [ ] Ordenar canciones por nombre
